# https://docs.drone.io/pipeline/environment/reference/

kind: pipeline
name: helloworld
type: docker

steps:
  - name: login-pages-1
    image: node:lts
    commands:
      - echo hello
      - echo world
      - echo $DRONE_BRANCH
      - cd login-pages-1
      - yarn
      - yarn test
      - yarn build
      - cd -
